[ID-26]Set appID and orgID for notifications
rokwire/polls-building-block pull request #27
Opened 2022-10-18 12:12 UTC by stefanvit

## Description
Adding the enviorment variables for appID and orgID used for the NotificationBB dependances.

**Resolves #59 

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

- [x] Immediately
- [ ] Within a week
- [ ] When possible

## Type of changes
Set new env variables for appID and orgID

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

2022-10-19 04:08 UTC, petyos requested changes
Hi @stefanvit , please look the feedback I left in https://github.com/rokwire/lms-building-block/pull/60 Here the situation is identical.

2022-10-19 04:08 UTC, petyos commented on CHANGELOG.md
> +- Fix docs [#21](https://github.com/rokwire/polls-building-block/issues/21)
You you have this here?

2022-11-16 07:27 UTC, petyos approved these changes
LGTM

2022-11-16 09:32 UTC, petyos approved these changes

2022-11-18 19:52 UTC, shurwit approved these changes
Thanks @stefanvit, LGTM!

2022-11-18 19:53 UTC, merged